Added missing flags and documentation to 'UserFlags.cs'.
KubaZ2/NetCord pull request #17
Opened 2024-03-26 03:28 UTC by Red-K0

2024-03-26 06:39 UTC, KubaZ2 commented
The names should be PascalCase. Could you also remove spaces before and after the `summary` content and after casting?

2024-03-26 08:05 UTC, Red-K0 commented
> The names should be PascalCase. Could you also replace spaces before and after the `summary` content with new lines and remove them after casting?
Yeah, all done.

2024-03-26 09:31 UTC, KubaZ2 commented
Could you also remove the 0 prefixes from bitfield values? They look odd for me. Also could you please split the values with new lines? I think it would make the code more readable.

2024-03-26 10:15 UTC, Red-K0 commented
> Could you also remove the 0 prefixes from bitfield values? They look odd for me. Also could you please split the values with new lines? I think it would make the code more readable.

Split and prefixes removed

2024-03-26 10:19 UTC, KubaZ2 commented
Could you also remove the empty spaces? I think it should be `Name = value` for all fields. I think the unnecessary indentation is useless.

2024-03-26 10:21 UTC, Red-K0 commented
> Could you also remove the empty spaces? I think it should be `Name = value` for all fields. I think the unnecessary indentation is useless.

Yeah that's more a remnant of how the code originally looked, removing it

2024-03-26 10:31 UTC, KubaZ2 requested changes

2024-03-26 10:31 UTC, KubaZ2 commented on NetCord/UserFlags.cs
> +
```suggestion
```

2024-03-26 10:42 UTC, Red-K0 commented
Not sure why it didn't go through the first time, but extra space is removed

2024-03-26 13:09 UTC, KubaZ2 commented
I reminded myself that https://github.com/KubaZ2/NetCord/blob/alpha/NetCord%2FPermissions.cs are formatted with uL suffix instead of casting. Could you follow that convention?

2024-03-27 09:39 UTC, Red-K0 commented
uL convention added

2024-03-27 10:22 UTC, KubaZ2 requested changes

2024-03-27 10:22 UTC, KubaZ2 commented on NetCord/UserFlags.cs
> +    /// User is a discord employee.
```suggestion
    /// User is a Discord employee.
```

2024-03-27 10:22 UTC, KubaZ2 commented on NetCord/UserFlags.cs
> +    /// User is a discord partner.
```suggestion
    /// User is a Discord partner.
```

2024-03-27 10:22 UTC, KubaZ2 commented on NetCord/UserFlags.cs
> +    Has_Unread_Urgent_Messages = 1uL << 13,
```suggestion
    HasUnreadUrgentMessages = 1uL << 13,
```

2024-03-30 18:53 UTC, KubaZ2 commented
Could you also fix casing of `private` when it follows `Undocumented and`?

2024-04-04 10:55 UTC, Red-K0 commented
Sorry for the delay, casings fixed

2024-04-04 14:27 UTC, KubaZ2 requested changes

2024-04-04 14:27 UTC, KubaZ2 commented on NetCord/UserFlags.cs
> +    PremiumPromoDismissed = 1uL << 5,
```suggestion
    PremiumPromotionDismissed = 1uL << 5,
```

2024-04-04 14:27 UTC, KubaZ2 commented on NetCord/UserFlags.cs
> +    /// Undocumented. User is the SYSTEM account.
```suggestion
    /// Undocumented. User is an Official Discord System user (part of the urgent message system).
```

2024-04-04 14:27 UTC, KubaZ2 commented on NetCord/UserFlags.cs
> +    /// Undocumented. User's account is disabled for spam.
I don't think it means the account is disabled. Other users have spammers' messages hidden by default as if they were blocked. Maybe something changed though.

2024-04-04 14:48 UTC, Red-K0 commented on NetCord/UserFlags.cs
> +    /// Undocumented. User's account is disabled for spam.
No discord can actually just disable you for spam, had it happen to someone I know.

> Discord has disabled your account for spam and/or platform abuse. Our anti-abuse measures may have flagged your account for any of the following behaviors:
> - Sending a large number of direct messages in a short span of time
> - Participating in a server dedicated to spamming Discord
> - Automating your user account or self-botting
> - Taking other actions on Discord — for example, joining a ton of servers — faster than humanly possible
> - Attempting potentially fraudulent activity

2024-04-04 14:54 UTC, KubaZ2 commented on NetCord/UserFlags.cs
> +    /// Undocumented. User's account is disabled for spam.
This is how being a spammer used to look like.
![image](https://github.com/KubaZ2/NetCord/assets/77853483/72cb147f-3b44-4fa6-aa2b-c95f19ea41fb)

2024-04-04 14:55 UTC, budgetdevv commented on NetCord/UserFlags.cs
> +    /// Undocumented. User's account is disabled for spam.
A spammer can be disabled or vice-versa. But even the non-disabled ones will have the flag, I checked in my own server @KubaZ2

2024-04-04 14:57 UTC, KubaZ2 commented on NetCord/UserFlags.cs
> +    /// Undocumented. User's account is disabled for spam.
thanks, that means that the comment isn't correct

2024-04-04 14:59 UTC, Red-K0 commented on NetCord/UserFlags.cs
> +    /// Undocumented. User's account is disabled for spam.
Yep, question is what to change it to though. I could just leave it at "User's account is disabled."

2024-04-04 15:01 UTC, budgetdevv commented on NetCord/UserFlags.cs
> +    /// Undocumented. User's account is disabled for spam.
"User account is flagged as spammer"

2024-04-04 15:09 UTC, Red-K0 commented on NetCord/UserFlags.cs
> +    /// Undocumented. User's account is disabled for spam.
Added that instead then

2024-04-06 10:29 UTC, merged