Update build to include PR's in workflows
KubaZ2/NetCord pull request #33
Opened 2024-08-08 14:32 UTC by csmir

Testing if this runs build

2024-08-08 14:35 UTC, KubaZ2 commented
It's not the best idea I think, because on pull request only activates when the pull request is created, it won't trigger for additional pushes to the source branch.

2024-08-08 14:35 UTC, KubaZ2 requested changes

2024-08-08 14:35 UTC, KubaZ2 commented on .github/workflows/build.yml
> +      branches: [ "alpha" ]
```suggestion
    branches: [ "alpha" ]
```

2024-08-08 14:43 UTC, csmir commented
It is not a bad idea I think, it will rerun the build process every time a new push is made to the pull request. It can even be installed that the PR *must* succeed build before being able to be merged.

2024-08-08 14:44 UTC, KubaZ2 requested changes

2024-08-08 14:44 UTC, KubaZ2 commented on .github/workflows/build.yml
> +    branches: [ "alpha" ]
```suggestion
    branches:
      - stable
      - alpha
```

2024-08-08 14:47 UTC, KubaZ2 commented
> It is not a bad idea I think, it will rerun the build process every time a new push is made to the pull request. It can even be installed that the PR _must_ succeed build before being able to be merged.

You are right, sorry, what do you think about adding `types: [opened, synchronize]`? That's what is used in https://github.com/NetCordDev/NetCord/blob/alpha/.github/workflows/documentation-preview.yml#L5

2024-08-08 14:51 UTC, csmir commented
> You are right, sorry, what do you think about adding `types: [opened, synchronize]`? That's what is used in https://github.com/NetCordDev/NetCord/blob/alpha/.github/workflows/documentation-preview.yml#L5

The only thing you lose out on in this circumstance is when the PR is reopened. All further logic remains the same. I honestly do not think it is necessary

2024-08-08 14:52 UTC, KubaZ2 commented
Not really, there are many activity types:
- assigned
- unassigned
- labeled
- unlabeled
- opened
- edited
- closed
- reopened
- synchronize
- converted_to_draft
- locked
- unlocked
- enqueued
- dequeued
- milestoned
- demilestoned
- ready_for_review
- review_requested
- review_request_removed
- auto_merge_enabled
- auto_merge_disable

Also I think running on reopened is not needed

2024-08-08 14:55 UTC, csmir commented
My bad, I read this:
![image](https://github.com/user-attachments/assets/6908dc76-49cc-472a-9e22-69a100491955)
and thought that was all it was

2024-08-08 14:56 UTC, KubaZ2 commented
Well, you are right then, we would only lose reopened there, though I still think reopened is not needed

2024-08-09 19:14 UTC, KubaZ2 requested changes

2024-08-09 19:14 UTC, KubaZ2 commented on .github/workflows/build.yml
> +    branches:
```suggestion
    types: [opened, synchronize]
    branches:
```

2024-08-09 19:16 UTC, merged

2024-08-09 19:16 UTC, KubaZ2 commented
Thanks!